### hyprpaper
## wallpapers or background image(s)

$wallpapers = ~/.config/background
$wallpaper1 = $wallpapers/skeleton.png
$wallpaper2 = $wallpapers/bug.png
$monitor1 = eDP-1
$monitor2 = HDMI-A-1
$mode = cover

wallpaper {
    monitor = $monitor1
    path = $wallpaper1
    fit_mode = $mode
}

wallpaper {
    monitor = $monitor2
    path = $wallpaper2
    fit_mode = $mode
}

splash = false
ipc = on
