### hyprpaper
## wallpapers or background image(s)

$wallpapers = ~/Pictures/backgrounds
$wallpaper1 = $wallpapers/cat-leaves.png
$wallpaper2 = $wallpapers/tux-wall.png
$monitor1 = eDP-1
$monitor2 = HDMI-A-1
$mode = cover

wallpaper {
    monitor = $monitor1
    path = $wallpaper1
    fit_mode = $mode
}

wallpaper {
    monitor = $monitor2
    path = $wallpaper2
    fit_mode = $mode
}

ipc = on
splash = false
