--- Default Programs
local terminal = "uwsm app -- kitty"
local terminalAlt = "uwsm app -- uxterm"
local browser = "uwsm app -- zen-browser"
local browserAlt = "uwsm app -- google-chrome-stable"
local fileManager = "uwsm app -- thunar"
local telegram = "uwsm app -- materialgram"
local discord = "uwsm app -- discord.sh"
local menu = "rofi -run-command 'uwsm app -- {cmd}' -show"
local emojiPick = "uwsm app -- it.mijorus.smile"
local editor = "uwsm app -- code-oss --disable-gpu"
local steam = "uwsm app -- steam-native"
local music = "uwsm app -- env LD_PRELOAD=spotify-adblock.so spotify"
local volumctrl = "uwsm app -- pavucontrol-qt"
local volumport = "uwsm app -- audiorelay"
local chatgpt = "xdg-open https://chatgpt.com"
local github = "xdg-open https://github.com"
local youtube = "xdg-open https://youtube.com"
