--- Window Rules

-- Layers
hl.layer_rule({match = {namespace = "waybar"}, blur = true})
hl.layer_rule({match = {namespace = "logout_dialog"}, blur = true})
hl.layer_rule({match = {namespace = "swaync-control-center"}, blur = true})
hl.layer_rule({match = {namespace = "swaync-control-center"}, ignore_alpha = 0.4})
hl.layer_rule({match = {namespace = "swaync-notification-window"}, blur = true})
hl.layer_rule({match = {namespace = "swaync-notification-window"}, ignore_alpha = 0.4})

-- Window Rule (part I)
hl.window_rule({match = {class = "^(gamescope)$"}, size = {1366, 926}, pseudo = true, maximize = false})
hl.window_rule({match = {class = "^(org.kde.kdeconnect.handler)$"}, float = true})
hl.window_rule({match = {class = "^(scrcpy)$"}, pseudo = true, tile = true, size = {490, 980}})
hl.window_rule({match = {class = "^(thunar)$"}, float = true, size = {900, 520}, move = {420, 280}})
hl.window_rule({match = {class = "^(kitty)$"}, size = {980, 620}, move = {520, 230}})
hl.window_rule({match = {class = "^(Waydroid)$"}, maximize = false})
hl.window_rule({match = {class = "^(pavucontrol-qt)$"}, maximize = true, workspace = 5, pseudo = true})
hl.window_rule({match = {class = "^(pavucontrol-qt)$"}, size = {1600, 920}})
hl.window_rule({match = {class = "^(io.github.kukuruzka165.materialgram)$"}, maximize = true, workspace = 4})
hl.window_rule({match = {class = "^(io.github.kukuruzka165.materialgram)$"}, pseudo = false, size = {1600, 900}})
hl.window_rule({match = {class = "^(com.obsproject.Studio)$"}, workspace = 6, maximize = true})
hl.window_rule({match = {class = "^(zenity)$"}, float = true, pseudo = true, tile = true})
hl.window_rule({match = {class = "^(mousepad)$"}, float = true, pseudo = true, tile = true})
hl.window_rule({match = {class = "^(xarchiver)$"}, float = true, pseudo = true, tile = true})
hl.window_rule({match = {class = "^(kvantummanager)$"}, float = true, pseudo = true, tile = true})
hl.window_rule({match = {class = "^(qt5ct)$"}, float = true, pseudo = true, tile = true})
hl.window_rule({match = {class = "^(qt6ct)$"}, float = true, pseudo = true, tile = true})
hl.window_rule({match = {class = "^(nwg-look)$"}, float = true, pseudo = true, tile = true})
hl.window_rule({match = {class = "^(lxappearance)$"}, float = true, pseudo = true, tile = true})
hl.window_rule({match = {class = "^(it.mijorus.smile)$"}, float = true, pseudo = true, tile = true})
hl.window_rule({match = {class = "^(blueman-manager)$"}, float = true, pseudo = true, tile = true})
hl.window_rule({match = {class = "^(nm-applet)$"}, float = true, pseudo = true, tile = true})
hl.window_rule({match = {class = "^(nm-connection-editor)$"}, float = true, pseudo = true, tile = true})
hl.window_rule({match = {class = "^(org.prismlauncher.PrismLauncher)$"}, float = true, pseudo = true, tile = true})

-- Window Rules (opacity)
hl.window_rule({match = {class = "^(kitty)$"}, opacity = "0.80 0.80 0.80"})
hl.window_rule({match = {class = "^(google-chrome)$"}, opacity = "0.90 0.90 0.90"})
hl.window_rule({match = {class = "^(Code)$"}, opacity = "0.90 0.90 0.90"})
hl.window_rule({match = {class = "^(steam)$"}, opacity = "0.90 0.90 0.90"})
hl.window_rule({match = {class = "^(code-url-handler)$"}, opacity = "0.90 0.90 0.90"})
hl.window_rule({match = {class = "^(code-insiders-url-handler)$"}, opacity = "0.90 0.90 0.90"})
hl.window_rule({match = {class = "^(nwg-look)$"}, opacity = "0.90 0.90 0.90"})
hl.window_rule({match = {class = "^(lxappearance)$"}, opacity = "0.90 0.90 0.90"})
hl.window_rule({match = {class = "^(qt5ct)$"}, opacity = "0.90 0.90 0.90"})
hl.window_rule({match = {class = "^(qt6ct)$"}, opacity = "0.90 0.90 0.90"})
hl.window_rule({match = {class = "^(thunar)$"}, opacity = "0.90 0.90 0.90"})
hl.window_rule({match = {class = "^(scrcpy)$"}, opacity = "0.90 0.90 0.90"})
hl.window_rule({match = {class = "^(org.kde.kdeconnect.handler)$"}, opacity = "0.90 0.90 0.90"})
hl.window_rule({match = {class = "^(kvantummanager)$"}, opacity = "0.90 0.90 0.90"})
hl.window_rule({match = {class = "^(pavucontrol-qt)$"}, opacity = "0.90 0.70 0.90"})
hl.window_rule({match = {class = "^(blueman-manager)$"}, opacity = "0.90 0.70 0.90"})
hl.window_rule({match = {class = "^(nm-applet)$"}, opacity = "0.90 0.70 0.90"})
hl.window_rule({match = {class = "^(spotify)$"}, opacity = "0.90 0.90 0.90"})
hl.window_rule({match = {class = "^(nm-connection-editor)$"}, opacity = "0.90 0.70 0.90"})
hl.window_rule({match = {class = "^(org.gnome.seahorse.Application)$"}, opacity = "0.90 0.70 0.90"})

-- Window Rules (workspaces)
hl.window_rule({match = {class = "^(zoom)$"}, workspace = 2})
hl.window_rule({match = {class = "^(code-oss)$"}, workspace = 2})
hl.window_rule({match = {class = "^(spotify)$"}, workspace = 3})
hl.window_rule({match = {class = "^(com.viber.Viber)$"}, workspace = 3})
hl.window_rule({match = {class = "^(io.github.kukuruzka165.materialgram)$"}, workspace = 4})
hl.window_rule({match = {class = "^(pavucontrol-qt)$"}, workspace = 5})
hl.window_rule({match = {class = "^(com.obsproject.Studio)$"}, workspace = 6})

-- Window Rules (opacity, again...)
hl.window_rule({opacity = "0.90 0.70 0.90", match = {class = "^(org.freedesktop.impl.portal.desktop.gtk)$"}})
hl.window_rule({opacity = "0.90 0.70 0.90", match = {class = "^(org.freedesktop.impl.portal.desktop.hyprland)$"}})
